package it.pa.repdgt.shared.exception;

import lombok.Getter;

@Getter
public enum CodiceErroreEnum {
	 C01("Errore Risorsa non trovata", "")
	,C02("Errore storicizazione ente", "")
	,C03("Errore Utente con ruolo DEGP/REGP non definito per il progetto", "")
	,C04("Errore Utente con ruolo DEG/REG non definito per il programma", "")
	,C05("Errore Utente con ruolo DEPP/REPP non definito per il progetto", "")
	,C06("Errore Combinazione (Programma,Progetto) non trovata", "")
	,C07("Errore integrazione dati utente", "")
	
	,G01("Errore Generico", "")
	,G02("Errore Richiesta errata", "")
	,G03("Errore Pagina richista non esistente", "")
	
	,R01("Errore Ruolo già esistente", "NOME RUOLO GIÀ IN USO")
	,R02("Errore impossibile aggiornare il ruolo", "")
	,R03("Errore impossibile cancellare il ruolo DTD/DSCU", "")
	,R04("Errore impossibile cancellare il ruoli predefiniti", "")
	,R05("Errore impossibile cancellare ruolo associato ad utente", "")
	,R06("Errore impossibile cancellare ruolo", "")
	,R07("Errore impossibile attivare il ruolo per l'utente", "")
	,R08("Errore Tipologia ruolo non presente", "")
	,R09("Errore Impossibile aggiornare ruolo predefinito", "")
	,R10("Errore Impossibile cancellare i ruoli di DTD e DSCU", "")
	,R11("Errore Impossibile cancellare i ruoli predefiniti", "")
	,R12("Errore Impossibile cancellare i ruoli associati agli utenti", "")
	,R13("Errore Impossibile assegnare un ruolo predefinito all'infuori di DTD e DSCU", "")
	,R14("Errore Il codice ruolo inserito non corrisponde a nessun ruolo esistente", "")
	,R15("Errore Impossibile cancellare un ruolo non associato all'utente", "")
	,RG01("Errore impossibile creare associazione ruolo al gruppo", "")
	,RG02("Errore impossibile aggiornare associazione ruolo al gruppo", "")
	
	,U01("Errore utente con codice fiscale già presente", "CODICE FISCALE GIÀ IN USO")
	,U02("Errore cancellazione utente con ruolo associato", "")
	,U03("Errore l'utente con codice fiscale possiede già il ruolo", "")
	,U04("Errore impossibile associare il ruolo all'utente", "")
	,U05("Errore Impossibile cancellare ruolo non associato all'utente", "")
	,U06("Errore ruolo non definito per l'utente", "")
	,U07("Errore utente con codice fiscale o numero documento già presente", "CODICE FISCALE GIÀ IN USO")
	,U08("Errore codice fiscale o numero documento non specificato", "")
	,U09("Errore impossibile aggiungere ruolo all'utente", "")
	,U10("Errore impossibile cancellare ruolo all'utente", "")
	,U11("Errore utente con id non trovato", "")
	,U12("Errore impossibile cancellare un utente che non esiste", "")
	,U13("Errore Impossibile cancellare l'utente con codice fiscale poiché ha almeno un ruolo associato", "")
	,U14("Errore Impossibile assegnare il ruolo con codice", "")
	,U15("Errore Impossibile assegnare il ruolo con codice poiché l'utente con id non esiste", "")
	,U16("Errore L'utente con id ha già il ruolo con codice assegnato", "RUOLO GIÀ ASSEGNATO ALL'UTENTE")
	,U17("Errore download immagine profilo utente", "")
	,U18("Errore Associazione tra utente e ruolo non trovata.", "")
	,U19("Errore export csv utenti", "")
	,U20("Errore utente con codice fiscale non esistente", "UTENTE NON TROVATO")
	,U21("Errore email utente già esistente", "EMAIL GIÀ IN USO")
	,U22("Errore upload immagine profilo ente", "")
	,U23("Errore utente con codice fiscale o numero documento già presente sul servizio indicato", "CITTADINO GIÀ ASSOCIATO AL SERVIZIO")
	,U24("Errore codice fiscale non disponibile", "")
	,S01("Errore file upload cittadino non valido", "CARICAMENTO NON RIUSCITO")
	,S02("Errore export csv servizio", "ELENCO NON SCARICATO")
	,S03("Errore servizio non accessibile per l'utente", "")
	,S04("Errore creazione servizio. Nessun questionario template associato al programma", "")
	,S05("Errore creazione servizio. Utente non ha ruolo FACILITATORE o VOLONTARIO", "")
	,S06("Errore aggiornare servizio. Utente non ha ruolo FACILITATORE o VOLONTARIO", "")
	,S07("Errore impossibile eliminare il servizio.", "")
	,S08("Errore creazione servizio. Servizio con stesso nome già esistente", "NOME SERVIZIO GIÀ IN USO")
	,S09("Errore servizio non esistente", "")
	,S10("Il servizio che vuoi creare riporta gli stessi dati di un servizio già esistente per la stessa data. Per creare una nuovo servizio, assicurati di differenziare almeno un’informazione, per esempio il nome o la descrizione", "")
	,S11("Errore creazione servizio", "")
	,S12("Risulta indicato più di un tipo di servizio prenotato", "")

	,SD01("Errore creazione sede", "NOME SEDE GIÀ IN USO")
	,SD02("Errore aggiornamento sede", "NUOVO NOME SEDE GIÀ IN USO")

	,Q01("Errore questionario template inesistente", "")
	,Q02("Errore Il questionario risulta già compilato", "")
	,QT01("Errore export csv questionari template", "ELENCO NON SCARICATO")
	,QT02("Errore impossibile aggiornare il questionario", "NUOVO NOME QUESTIONARIO GIÀ IN USO")
	,QT03("Errore impossibile cancellare il questionario", "")
	,QT04("Errore impossibile recuperare il questionario poichè inesistente su MongoDB", "")
	,QT05("Errore impossibile recuperare il questionario poichè inesistente su MySql", "")
	,QT06("Errore impossibile avere un programma senza associato alcun questionario template", "")
	,QT07("Errore impossibile salvare il questionario template perchè id questionario template già esistente", "")
	,QT08("Errore creazione questionario compilato. SezioneQuestionarioQ3 attualmente associata al servizio del cittadino non presente su MongoDB.", "")

	,QC01("Errore questionario compilato non presente su mySql", "")
	,QC02("Errore questionario compilato non presente su MongoDB", "")
	
	,CIT01("Errore upload cittadini", "CARICAMENTO NON RIUSCITO")
	,CIT02("Errore impossibile aggiornare cittadino", "")
	,CIT03("Errore export csv cittadini", "ELENCO NON SCARICATO")
	
	,E01("Errore invio email", "")
	
	,EN01("Errore export csv enti", "ELENCO NON SCARICATO")
	,EN02("Errore file upload enti non valido", "CARICAMENTO NON RIUSCITO")
	,EN03("Errore Impossibile assegnare ente come gestore del programma", "")
	,EN04("Errore Impossibile assegnare referente/delegato ente partner per progetto", "REFERENTE O DELEGATO GIÀ ASSOCIATO ALL'ENTE")
	,EN05("Errore file upload enti partner non valido", "CARICAMENTO NON RIUSCITO")
	,EN06("Errore Impossibile terminare/cancellare associazione referente", "RIMOZIONE NON CONSENTITA")
	,EN07("Errore Impossibile associare facilitatore/volontario sulla sede-ente-progetto", "FACILITATORE O VOLONTARIO GIÀ ASSOCIATO")
	,EN08("Errore Impossibile cancellare associazione facilitatore/volontario sulla sede-ente-progetto", "RIMOZIONE NON CONSENTITA")
	,EN09("Errore Impossibile terminare/cancellare associazione Ente-Sede-Progetto", "")
	,EN10("Errore ente con partita iva già presente", "CODICE FISCALE GIÀ IN USO")
	,EN11("Errore Impossibile assegnare referente/delegato ente gestore programma per il programma ", "REFERENTE O DELEGATO GIÀ ASSOCIATO ALL'ENTE")
	,EN12("Errore Impossibile assegnare referente/delegato ente gestore progetto per il progetto ", "REFERENTE O DELEGATO GIÀ ASSOCIATO ALL'ENTE")
	,EN13("Errore Impossibile aggiornare ente", "")
	,EN14("Errore Impossibile modificare ente gestore programma", "NUOVO CODICE FISCALE GIÀ IN USO")
	,EN15("Errore Impossibile modificare ente gestore progetto", "")
	,EN16("Errore Impossibile cancellare ente partner per progetto", "RIMOZIONE NON RIUSCITA")
	,EN17("Errore Impossibile cancellare ente gestore programma per programma", "RIMOZIONE NON RIUSCITA")
	,EN18("Errore Impossibile cancellare ente gestore progetto per progetto", "RIMOZIONE NON RIUSCITA")
	,EN19("Errore Impossibile terminare ente gestore programma per programma", "RIMOZIONE NON RIUSCITA")
	,EN20("Errore Impossibile terminare ente gestore progetto per progetto", "RIMOZIONE NON RIUSCITA")
	,EN21("Errore Impossibile terminare ente partner per progetto", "RIMOZIONE NON RIUSCITA")
	,EN22("Errore Impossibile terminare referente/delegato gestore programma", "RIMOZIONE NON CONSENTITA")
	,EN23("Errore Impossibile terminare referente/delegato gestore progetto", "RIMOZIONE NON CONSENTITA")
	,EN24("Errore Ente partner non presente per idEnte idProgetto indicati", "")
	,EN25("Errore Ente con stesso nome già esistente", "NOME ENTE GIÀ IN USO")
	,EN26("Errore L'ente risulta essere già associato al progetto come ente gestore", "ENTE GIÀ ASSOCIATO")
	,EN27("Errore L'ente risulta essere già associato al progetto come ente partner", "ENTE GIÀ ASSOCIATO")
	
	,T01("Errore token non valido", "")
	,T02("Errore token scaduto", "")
	
	,P01("Errore creazione programma", "ID PROGRAMMA GIÀ IN USO")
	,P02("Errore creazione programma. Questionario template default associato non esistente", "")
	,P03("Errore impossibile terminare programma", "")
	,P04("Errore impossibile cancellare programma", "")
	,P05("Errore impossibile assegnare programma ad ente gestore", "")
	,P06("Errore impossibile aggiornare programma", "NUOVO ID PROGRAMMA GIÀ IN USO")
	,P07("Errore impossibile associare questionario al programma", "")
	,P08("Errore export csv programmi", "ELENCO NON SCARICATO")
	
	,PR01("Errore creazione progetto", "")
	,PR02("Errore impossibile cancellare progetto", "")
	,PR03("Errore impossibile terminare progetto", "")
	,PR04("Errore impossibile aggiornare progetto", "")
	,PR05("Errore impossibile assegnare progetto ad ente gestore", "")
	,PR06("Errore impossibile assegnare progetto ad al programma", "")
	,PR07("Errore attivare progetto", "")
	,PR08("Errore export csv progetti", "ELENCO NON SCARICATO")
	,PR09("Errore Impossibile Assegnare gestore progetto per il progetto. Unico Facilitatore o Volontario attivo sul progetto", "OPERAZIONE NON RIUSCITA")
	
	,D01("Errore chiamata servizio Drupal", "SI È VERIFICATO UN ERRORE")
	
	,WD01("Errore creazione utente Workdocs", "REGISTRAZIONE NON RIUSCITA")
	,WD02("Errore attivazione utente Workdocs", "REGISTRAZIONE NON RIUSCITA")
	
	,RC01("Errore tecnico creazione utente RocketChat", "ACCESSO ALLA CHAT NON RIUSCITO")
	,RC02("Errore creazione utente RocketChat", "ACCESSO ALLA CHAT NON RIUSCITO")
	,RC03("Errore recupero token utente RocketChat", "ACCESSO ALLA CHAT NON RIUSCITO")
	
	,A02("Errore tentativo accesso a risorsa non permesso", "")
	,A03("Non si dispone dei permessi per compilare il questionario", "Il tuo ruolo su Facilita risulta in sospeso")
	,A04("Sezionario q4 completamente mancante, almeno una risposta deve essere selezionata", "")
	,A05("La sezione q4 e' stata compilata ma nessuna risposta e' stata selezionata", "")
	,A06("La data del servizio non rientra all’interno delle date di progetto", "ERRORE DATA SERVIZIO")

	,CM01("E' già in corso un inserimento dati", "IMPOSSIBILE AVVIARE INSERIMENTO DATI")
	,CM02("Errore recupero finestra di caricamento", "IMPOSSIBILE RECUPERARE FINESTRA CARICAMENTO")
	
	,M01("Configurazione minorenni non trovata", "")
	,M02("Impossibile modificare la configurazione minorenni poiché essa è abilitata", "")
	,M03("La data decorrenza non è compresa tra le date di inizio e fine del programma", "")
	,M04("L'intervento inserito non è coerente con l'intervento del programma", "")
	,M05("Configurazione minorenni già esistente per il programma", "")
	,ZD00("Errore generico Zendesk", "")
	;
	
	private String descrizioneErrore;
	private String titolo;
	
	private CodiceErroreEnum(String descrizioneErrore, String titolo) {
		this.descrizioneErrore = descrizioneErrore;
		this.titolo = titolo;
	}
}