package it.pa.repdgt.gestioneutente.repository;

import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import it.pa.repdgt.shared.entity.UtenteEntity;

@Repository
public interface UtenteRepository extends JpaRepository<UtenteEntity, Long> { 

//	@Query(value = "SELECT * FROM UENTE WHERE codiceFiscale = :codiceFiscale", nativeQuery = true)
//	@Query(value = "SELECT u FROM UtenteEntity u WHERE u.codiceFiscale = :codiceFiscale ")
//	public UtenteEntity findByCodiceFiscale(String codiceFiscale);
	
	public Optional<UtenteEntity> findByCodiceFiscale(String codiceFiscaleUtente);
	
	@Query(value = "SELECT utente FROM UtenteEntity utente WHERE utente.codiceFiscale = :theCodiceFiscale")
	public UtenteEntity findUtenteEagerByCodiceFiscale(@Param(value = "theCodiceFiscale") String theCodiceFiscale);
	
	@Query(value = " "
				 + "SELECT * "
				 + "	FROM  ("
				 + "    	SELECT utente_and_stato.id,"
				 + "           utente_and_stato.codice_fiscale,"
				 + "           utente_and_stato.cognome,"
				 + "           utente_and_stato.email,"
				 + "           utente_and_stato.nome,"
				 + "           utente_and_stato.stato_utente as stato,"
				 + "           utente_and_stato.telefono,"
				 + "           utente_and_stato.mansione,"
				 + "           utente_and_stato.tipo_contratto,"
				 + "           utente_and_stato.consenso_dati,"
				 + "           utente_and_stato.data_ora_consenso_dati,"
				 + "           utente_and_stato.data_ora_aggiornamento,"
				 + "           utente_and_stato.data_ora_creazione,"
				 + "           utente_and_stato.integrazione,"
				 + "           utente_and_stato.immagine_profilo"
				 + "    		FROM ( "
				 + "    			SELECT utente.*, case when (SELECT distinct u.ID "
				 + "                	FROM utente u "
				 + "                    	INNER JOIN utente_x_ruolo uxr "
				 + "                        	ON u.codice_fiscale = uxr.utente_id "
				 + "                    WHERE u.id = utente.id ) is null then 'NON ATTIVO' "
				 + "                                else 'ATTIVO' "
				 + "                                end as stato_utente "
				 + "                	FROM "
				 + "                    	utente utente "
				 + "                    WHERE 1=1 "
				 + "         			AND    (     :criterioRicerca IS NULL  "
                 + "               			OR CONVERT( utente.ID, CHAR ) = :criterioRicerca "
                 + "              			OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
                 + "              			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
                 + "                        concat(UPPER( utente.COGNOME ), ' ' , UPPER( utente.NOME ))  = UPPER(:criterioRicerca) "
                 + "              			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike ) ) "
				 + "                    AND ( "
				 + "						 SELECT distinct u2.id "
				 + "                         	FROM utente u2 "
				 + "                            	LEFT JOIN utente_x_ruolo ur2 "
				 + "                                   ON u2.CODICE_FISCALE = ur2.UTENTE_ID "
				 + "                                LEFT JOIN ruolo ruolo2"
				 + "                                   ON ruolo2.CODICE = ur2.RUOLO_CODICE "
				 + "                            WHERE 1=1 "
				 + "                            	AND u2.id = utente.id "
				 + "                                AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id ) utente_and_stato "
				 + "     WHERE 1=1 "
				 + "     	AND (COALESCE(:stati) IS NULL OR  utente_and_stato.stato_utente in (:stati)) "
				 + "   		ORDER BY utente_and_stato.ID ASC "
				 + "   	 	LIMIT :currPageIndex, :pageSize ) as utentiPaginati "
				 + "	LEFT JOIN utente_x_ruolo ur"
				 + "    	ON utentiPaginati.CODICE_FISCALE = ur.UTENTE_ID "
				 + "    LEFT JOIN ruolo ruolo "
				 + "        ON ruolo.CODICE = ur.RUOLO_CODICE ",
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiByFiltri(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "stati") List<String> stati,
			@Param(value = "currPageIndex") Integer currPageIndex,
			@Param(value = "pageSize") Integer pageSize
	);
	
	@Query(value = ""
			+ "SELECT * FROM ( "
			+ "		SELECT * "
			+ "     	FROM ( "
			+ "            SELECT distinct rdg.CF_UTENTE "
			+ "                 FROM referente_delegati_gestore_programma  rdg "
			+ "                 	INNER JOIN programma programma"
			+ "                     	ON rdg.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdgp.CF_UTENTE"
			+ "                 FROM referente_delegati_gestore_progetto rdgp"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON rdgp.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                 	ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdp.CF_UTENTE"
			+ "                 FROM referente_delegati_partner rdp"
			+ "                 INNER JOIN ente_partner ep"
			+ "                     ON rdp.ID_PROGETTO = ep.ID_PROGETTO"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON ep.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                     ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'"
			+ " "
			+ "              UNION "
			+ " "
			+ "              SELECT distinct espf.ID_FACILITATORE"
			+ "                 FROM ente_sede_progetto_facilitatore espf"
			+ "              WHERE espf.RUOLO_UTENTE = 'VOL'"
			+ "			) AS utenti_per_ruolo  "
			+ "         	INNER JOIN utente utente"
			+ "             	ON utenti_per_ruolo.CF_UTENTE = utente.CODICE_FISCALE"
			+ " "
			+ "             WHERE 1=1"
			+ "                   AND    (    :criterioRicerca IS NULL   "
			+ "                   		   OR CONVERT( utente.ID, CHAR ) = :criterioRicerca  "
			+ "                            OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "                      )"
			+ "                	  AND"
			+ "                   ( SELECT distinct u2.id"
			+ "                       FROM utente u2"
			+ "                          LEFT JOIN utente_x_ruolo ur2"
			+ "                             ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "                          LEFT JOIN ruolo ruolo2"
			+ "                             ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "                      WHERE 1=1"
			+ "                          AND u2.id = utente.id"
			+ "                          AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id"
			+ "             ORDER BY utente.id"
			+ "             LIMIT :currPageIndex, :pageSize"
			+ "            ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur"
			+ "                   ON ur.UTENTE_ID = risultato.CODICE_FISCALE"
			+ "             INNER JOIN ruolo ruolo   "
			+ "                   ON ruolo.CODICE = ur.RUOLO_CODICE  ",
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerDSCU(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "currPageIndex") Integer currPageIndex,
			@Param(value = "pageSize")  Integer pageSize
	);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_programma rdg "
			+ "			 	WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 		AND rdg.CF_UTENTE != :cfUtente"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_progetto rdgp "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON rdgp.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "			 	FROM referente_delegati_partner rdp "
			+ "			 	INNER JOIN ente_partner ep "
			+ "			 		ON rdp.ID_PROGETTO = ep.ID_PROGETTO "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON ep.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma "
			+ "             UNION"
			+ "             SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					   )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			      ORDER BY utente.id"
			+ "			      LIMIT :currPageIndex, :pageSize"
			+ "               ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoGestoreProgramma(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "currPageIndex") Integer currPageIndex,
			@Param(value = "pageSize")  Integer pageSize
	);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			   FROM referente_delegati_gestore_programma rdg "
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp"
			+ "				WHERE rdgp.CF_UTENTE != :cfUtente "
			+ "					AND rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.ID_PROGETTO = :idProgetto "
			+ "          UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "					    OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "						)"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			             	FROM utente u2"
			+ "			                LEFT JOIN utente_x_ruolo ur2"
			+ "			                	ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                LEFT JOIN ruolo ruolo2"
			+ "			                    ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                WHERE 1=1"
			+ "			                    AND u2.id = utente.id"
			+ "			                    AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "			              LIMIT :currPageIndex, :pageSize"
			+ "                          ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoGestoreProgetti(
			@Param(value = "idProgramma") Long idProgramma,
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente, 
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "currPageIndex")  Integer currPageIndex,
			@Param(value = "pageSize")  Integer pageSize
	);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE"
			+ "				FROM referente_delegati_gestore_programma rdg"
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma "
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp "
			+ "				WHERE rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.CF_UTENTE != :cfUtente"
			+ "					AND rdp.ID_PROGETTO = :idProgetto"
			+ "                UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "			   		AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					  	 )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "			              LIMIT :currPageIndex, :pageSize"
			+ "                          ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE",
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoEntePartnerProgetti(
			@Param(value = "idProgramma") Long idProgramma,
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente, 
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "currPageIndex")  Integer currPageIndex,
			@Param(value = "pageSize")  Integer pageSize
	);
	
	@Query(value = " "
			 + "SELECT * "
			 + "	FROM ( "
			 + "          SELECT utente_and_stato.stato_utente as stato"
			 + "    		FROM ( "
			 + "    			SELECT utente.*, case when (SELECT distinct u.ID "
			 + "                	FROM utente u "
			 + "                    	INNER JOIN utente_x_ruolo uxr "
			 + "                        	ON u.codice_fiscale = uxr.utente_id "
			 + "                    WHERE u.id = utente.id ) is null then 'NON ATTIVO' "
			 + "                                else 'ATTIVO' "
			 + "                                end as stato_utente "
			 + "                	FROM "
			 + "                    	utente utente "
			 + "                    WHERE 1=1 "
			 + "         			AND    (     :criterioRicerca IS NULL  "
             + "               			OR CONVERT( utente.ID, CHAR ) = :criterioRicerca "
             + "              			OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike ) ) "
			 + "                    AND ( "
			 + "						 SELECT distinct u2.id "
			 + "                         	FROM utente u2 "
			 + "                            	LEFT JOIN utente_x_ruolo ur2 "
			 + "                                   ON u2.CODICE_FISCALE = ur2.UTENTE_ID "
			 + "                                LEFT JOIN ruolo ruolo2"
			 + "                                   ON ruolo2.CODICE = ur2.RUOLO_CODICE "
			 + "                            WHERE 1=1 "
			 + "                            	AND u2.id = utente.id "
			 + "                                AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id ) utente_and_stato "
			 + "     WHERE 1=1 "
			 + "     	AND (COALESCE(:stati) IS NULL OR  utente_and_stato.stato_utente in (:stati)) "
			 + "   		 ) as utentiPaginati ",
		nativeQuery = true)
	public Set<String> findStatiByFilter(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "stati") List<String> stati
	);

	@Query(value = " "
			 + "SELECT distinct ruolo.nome "
			 + "	FROM  ("
			 + "    	SELECT utente_and_stato.id,"
			 + "           utente_and_stato.codice_fiscale,"
			 + "           utente_and_stato.cognome,"
			 + "           utente_and_stato.email,"
			 + "           utente_and_stato.nome,"
			 + "           utente_and_stato.stato_utente as stato,"
			 + "           utente_and_stato.telefono,"
			 + "           utente_and_stato.mansione,"
			 + "           utente_and_stato.tipo_contratto,"
			 + "           utente_and_stato.consenso_dati,"
			 + "           utente_and_stato.data_ora_consenso_dati,"
			 + "           utente_and_stato.data_ora_aggiornamento,"
			 + "           utente_and_stato.data_ora_creazione,"
			 + "           utente_and_stato.integrazione"
			 + "    		FROM ( "
			 + "    			SELECT utente.*, case when (SELECT distinct u.ID "
			 + "                	FROM utente u "
			 + "                    	INNER JOIN utente_x_ruolo uxr "
			 + "                        	ON u.codice_fiscale = uxr.utente_id "
			 + "                    WHERE u.id = utente.id ) is null then 'NON ATTIVO' "
			 + "                                else 'ATTIVO' "
			 + "                                end as stato_utente "
			 + "                	FROM "
			 + "                    	utente utente "
			 + "                    WHERE 1=1 "
			 + "         			AND    (     :criterioRicerca IS NULL  "
             + "               			OR CONVERT( utente.ID, CHAR ) = :criterioRicerca "
             + "              			OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike ) ) "
			 + "                    AND ( "
			 + "						 SELECT distinct u2.id "
			 + "                         	FROM utente u2 "
			 + "                            	LEFT JOIN utente_x_ruolo ur2 "
			 + "                                   ON u2.CODICE_FISCALE = ur2.UTENTE_ID "
			 + "                                LEFT JOIN ruolo ruolo2"
			 + "                                   ON ruolo2.CODICE = ur2.RUOLO_CODICE "
			 + "                            WHERE 1=1 "
			 + "                            	AND u2.id = utente.id "
			 + "                                AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id ) utente_and_stato "
			 + "     WHERE 1=1 "
			 + "     	AND (COALESCE(:stati) IS NULL OR  utente_and_stato.stato_utente in (:stati)) "
			 + "   		ORDER BY utente_and_stato.ID ASC "
			 + "   	 	 ) as utentiPaginati "
			 + "	LEFT JOIN utente_x_ruolo ur"
			 + "    	ON utentiPaginati.CODICE_FISCALE = ur.UTENTE_ID "
			 + "    LEFT JOIN ruolo ruolo "
			 + "        ON ruolo.CODICE = ur.RUOLO_CODICE ",
		nativeQuery = true)
	public List<String> findAllRuoli(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,  
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "stati") List<String> stati
	);

	@Query(value = ""
			+ "SELECT distinct ruolo.nome FROM ( "
			+ "		SELECT * "
			+ "     	FROM ( "
			+ "            SELECT distinct rdg.CF_UTENTE "
			+ "                 FROM referente_delegati_gestore_programma  rdg "
			+ "                 	INNER JOIN programma programma"
			+ "                     	ON rdg.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdgp.CF_UTENTE"
			+ "                 FROM referente_delegati_gestore_progetto rdgp"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON rdgp.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                 	ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdp.CF_UTENTE"
			+ "                 FROM referente_delegati_partner rdp"
			+ "                 INNER JOIN ente_partner ep"
			+ "                     ON rdp.ID_PROGETTO = ep.ID_PROGETTO"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON ep.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                     ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'"
			+ " "
			+ "              UNION "
			+ " "
			+ "              SELECT distinct espf.ID_FACILITATORE"
			+ "                 FROM ente_sede_progetto_facilitatore espf"
			+ "              WHERE espf.RUOLO_UTENTE = 'VOL'"
			+ "			) AS utenti_per_ruolo  "
			+ "         	INNER JOIN utente utente"
			+ "             	ON utenti_per_ruolo.CF_UTENTE = utente.CODICE_FISCALE"
			+ " "
			+ "             WHERE 1=1"
			+ "                   AND    (    :criterioRicerca IS NULL   "
			+ "                   		   OR CONVERT( utente.ID, CHAR ) = :criterioRicerca  "
			+ "                            OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "                      )"
			+ "                	  AND"
			+ "                   ( SELECT distinct u2.id"
			+ "                       FROM utente u2"
			+ "                          LEFT JOIN utente_x_ruolo ur2"
			+ "                             ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "                          LEFT JOIN ruolo ruolo2"
			+ "                             ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "                      WHERE 1=1"
			+ "                          AND u2.id = utente.id"
			+ "                          AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id"
			+ "             ORDER BY utente.id"
			+ "            ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur"
			+ "                   ON ur.UTENTE_ID = risultato.CODICE_FISCALE"
			+ "             INNER JOIN ruolo ruolo   "
			+ "                   ON ruolo.CODICE = ur.RUOLO_CODICE  ",
			nativeQuery = true)
	public List<String> findRuoliPerDSCU(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,  
			@Param(value = "ruoli") List<String> ruoli
	);

	@Query(value = "SELECT distinct ruolo.nome FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_programma rdg "
			+ "			 	WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 		AND rdg.CF_UTENTE != :cfUtente"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_progetto rdgp "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON rdgp.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "			 	FROM referente_delegati_partner rdp "
			+ "			 	INNER JOIN ente_partner ep "
			+ "			 		ON rdp.ID_PROGETTO = ep.ID_PROGETTO "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON ep.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma "
			+ "             UNION"
			+ "             SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					   )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			      ORDER BY utente.id"
			+ "               ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public List<String> findRuoliPerReferenteDelegatoGestoreProgramma(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli
	);

	@Query(value = "SELECT distinct ruolo.nome FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			   FROM referente_delegati_gestore_programma rdg "
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp"
			+ "				WHERE rdgp.CF_UTENTE != :cfUtente "
			+ "					AND rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.ID_PROGETTO = :idProgetto "
			+ "          UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "					    OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "						)"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			             	FROM utente u2"
			+ "			                LEFT JOIN utente_x_ruolo ur2"
			+ "			                	ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                LEFT JOIN ruolo ruolo2"
			+ "			                    ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                WHERE 1=1"
			+ "			                    AND u2.id = utente.id"
			+ "			                    AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "                          ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public List<String> findRuoliPerReferenteDelegatoGestoreProgetti(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "idProgetto") Long idProgetto, 
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli
	);

	@Query(value = "SELECT distinct ruolo.nome FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE"
			+ "				FROM referente_delegati_gestore_programma rdg"
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma "
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp "
			+ "				WHERE rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.CF_UTENTE != :cfUtente"
			+ "					AND rdp.ID_PROGETTO = :idProgetto"
			+ "                UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "			   		AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					  	 )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "                      ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE",
			nativeQuery = true)
	public List<String> findRuoliPerReferenteDelegatoEntePartnerProgetti(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli
	);

	@Query(value = ""
			+ " SELECT "
			+ "		*  "
			+ " FROM   "
			+ "		utente "
			+ "	WHERE 1=1  "
			+ "		AND (   "
			+ "			   CONVERT( utente.ID, CHAR ) = :criterioRicerca ) "
		    + "	    	   OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
            + "			   OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
            + "			   OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike "
            + "		) ", 
			nativeQuery = true)
	public List<UtenteEntity> findUtenteByCriterioRicerca(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike
	);

	public Optional<UtenteEntity> findByEmailAndCodiceFiscaleNot(String email, String codiceFiscale);

	@Query(value = " "
			 + "SELECT count(*) "
			 + "	FROM  ("
			 + "    	SELECT *"
			 + "    		FROM ( "
			 + "    			SELECT utente.*, case when (SELECT distinct u.ID "
			 + "                	FROM utente u "
			 + "                    	INNER JOIN utente_x_ruolo uxr "
			 + "                        	ON u.codice_fiscale = uxr.utente_id "
			 + "                    WHERE u.id = utente.id ) is null then 'NON ATTIVO' "
			 + "                                else 'ATTIVO' "
			 + "                                end as stato_utente "
			 + "                	FROM "
			 + "                    	utente utente "
			 + "                    WHERE 1=1 "
			 + "         			AND    (     :criterioRicerca IS NULL  "
             + "               			OR CONVERT( utente.ID, CHAR ) = :criterioRicerca "
             + "              			OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
             + "              			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike ) ) "
			 + "                    AND ( "
			 + "						 SELECT distinct u2.id "
			 + "                         	FROM utente u2 "
			 + "                            	LEFT JOIN utente_x_ruolo ur2 "
			 + "                                   ON u2.CODICE_FISCALE = ur2.UTENTE_ID "
			 + "                                LEFT JOIN ruolo ruolo2"
			 + "                                   ON ruolo2.CODICE = ur2.RUOLO_CODICE "
			 + "                            WHERE 1=1 "
			 + "                            	AND u2.id = utente.id "
			 + "                                AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id ) utente_and_stato "
			 + "     WHERE 1=1 "
			 + "     	AND (COALESCE(:stati) IS NULL OR  utente_and_stato.stato_utente in (:stati)) "
			 + "   	 ) as utentiPaginati ",
		nativeQuery = true)
	public int countUtentiTrovati(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "stati") List<String> stati);

	@Query(value = ""
			+ "SELECT count(*) FROM ( "
			+ "		SELECT * "
			+ "     	FROM ( "
			+ "            SELECT distinct rdg.CF_UTENTE "
			+ "                 FROM referente_delegati_gestore_programma  rdg "
			+ "                 	INNER JOIN programma programma"
			+ "                     	ON rdg.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdgp.CF_UTENTE"
			+ "                 FROM referente_delegati_gestore_progetto rdgp"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON rdgp.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                 	ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdp.CF_UTENTE"
			+ "                 FROM referente_delegati_partner rdp"
			+ "                 INNER JOIN ente_partner ep"
			+ "                     ON rdp.ID_PROGETTO = ep.ID_PROGETTO"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON ep.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                     ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'"
			+ " "
			+ "              UNION "
			+ " "
			+ "              SELECT distinct espf.ID_FACILITATORE"
			+ "                 FROM ente_sede_progetto_facilitatore espf"
			+ "              WHERE espf.RUOLO_UTENTE = 'VOL'"
			+ "			) AS utenti_per_ruolo  "
			+ "         	INNER JOIN utente utente"
			+ "             	ON utenti_per_ruolo.CF_UTENTE = utente.CODICE_FISCALE"
			+ " "
			+ "             WHERE 1=1"
			+ "                   AND    (    :criterioRicerca IS NULL   "
			+ "                   		   OR CONVERT( utente.ID, CHAR ) = :criterioRicerca  "
			+ "                            OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "                      )"
			+ "                	  AND"
			+ "                   ( SELECT distinct u2.id"
			+ "                       FROM utente u2"
			+ "                          LEFT JOIN utente_x_ruolo ur2"
			+ "                             ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "                          LEFT JOIN ruolo ruolo2"
			+ "                             ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "                      WHERE 1=1"
			+ "                          AND u2.id = utente.id"
			+ "                          AND  ( COALESCE(:ruolo) IS NULL   OR   ruolo2.nome IN ( :ruolo) )) = utente.id"
			+ "            ) as risultato",
			nativeQuery = true)
	public int countUtentiTrovatiPerDSCU(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,
			@Param(value = "ruolo") List<String> ruolo);

	@Query(value = "SELECT count(*) FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_programma rdg "
			+ "			 	WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 		AND rdg.CF_UTENTE != :cfUtente"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_progetto rdgp "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON rdgp.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "			 	FROM referente_delegati_partner rdp "
			+ "			 	INNER JOIN ente_partner ep "
			+ "			 		ON rdp.ID_PROGETTO = ep.ID_PROGETTO "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON ep.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma "
			+ "             UNION"
			+ "             SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					   )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruolo) IS NULL   OR   ruolo2.nome IN (:ruolo) )) = utente.id"
			+ "               ) as risultato",
			nativeQuery = true)
	public int countUtentiTrovatiPerReferenteDelegatoGestoreProgramma(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruolo") List<String> ruolo);

	@Query(value = "SELECT count(*) FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			   FROM referente_delegati_gestore_programma rdg "
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp"
			+ "				WHERE rdgp.CF_UTENTE != :cfUtente "
			+ "					AND rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.ID_PROGETTO = :idProgetto "
			+ "          UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "					    OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "						)"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			             	FROM utente u2"
			+ "			                LEFT JOIN utente_x_ruolo ur2"
			+ "			                	ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                LEFT JOIN ruolo ruolo2"
			+ "			                    ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                WHERE 1=1"
			+ "			                    AND u2.id = utente.id"
			+ "			                    AND  ( COALESCE(:ruolo) IS NULL   OR   ruolo2.nome IN (:ruolo) )) = utente.id"
			+ "                          ) as risultato",
			nativeQuery = true)
	public int countUtentiTrovatiPerReferenteDelegatoGestoreProgetti(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruolo") List<String> ruolo);

	@Query(value = "SELECT count(*) FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE"
			+ "				FROM referente_delegati_gestore_programma rdg"
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma "
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp "
			+ "				WHERE rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.CF_UTENTE != :cfUtente"
			+ "					AND rdp.ID_PROGETTO = :idProgetto"
			+ "                UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "			   		AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					  	 )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruolo) IS NULL   OR   ruolo2.nome IN (:ruolo) )) = utente.id"
			+ "                          ) as risultato",
			nativeQuery = true)
	public int countUtentiTrovatiPerReferenteDelegatoEntePartnerProgetti(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruolo") List<String> ruolo);

	@Query(value = " "
			 + "SELECT * "
			 + "	FROM  ("
			 + "    	SELECT utente_and_stato.id,"
			 + "           utente_and_stato.codice_fiscale,"
			 + "           utente_and_stato.cognome,"
			 + "           utente_and_stato.email,"
			 + "           utente_and_stato.nome,"
			 + "           utente_and_stato.stato_utente as stato,"
			 + "           utente_and_stato.telefono,"
			 + "           utente_and_stato.mansione,"
			 + "           utente_and_stato.tipo_contratto,"
			 + "           utente_and_stato.consenso_dati,"
			 + "           utente_and_stato.data_ora_consenso_dati,"
			 + "           utente_and_stato.data_ora_aggiornamento,"
			 + "           utente_and_stato.data_ora_creazione,"
			 + "           utente_and_stato.integrazione,"
			 + "		   utente_and_stato.immagine_profilo"
			 + "    		FROM ( "
			 + "    			SELECT utente.*, case when (SELECT distinct u.ID "
			 + "                	FROM utente u "
			 + "                    	INNER JOIN utente_x_ruolo uxr "
			 + "                        	ON u.codice_fiscale = uxr.utente_id "
			 + "                    WHERE u.id = utente.id ) is null then 'NON ATTIVO' "
			 + "                                else 'ATTIVO' "
			 + "                                end as stato_utente "
			 + "                	FROM "
			 + "                    	utente utente "
			 + "                    WHERE 1=1 "
			 + "         			AND    (     :criterioRicerca IS NULL  "
            + "               			OR CONVERT( utente.ID, CHAR ) = :criterioRicerca "
            + "              			OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
            + "              			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
            + "              			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike ) ) "
			 + "                    AND ( "
			 + "						 SELECT distinct u2.id "
			 + "                         	FROM utente u2 "
			 + "                            	LEFT JOIN utente_x_ruolo ur2 "
			 + "                                   ON u2.CODICE_FISCALE = ur2.UTENTE_ID "
			 + "                                LEFT JOIN ruolo ruolo2"
			 + "                                   ON ruolo2.CODICE = ur2.RUOLO_CODICE "
			 + "                            WHERE 1=1 "
			 + "                            	AND u2.id = utente.id "
			 + "                                AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id ) utente_and_stato "
			 + "     WHERE 1=1 "
			 + "     	AND (COALESCE(:stati) IS NULL OR  utente_and_stato.stato_utente in (:stati)) "
			 + "   		ORDER BY utente_and_stato.ID ASC "
			 + "   	 	) as utentiPaginati "
			 + "	LEFT JOIN utente_x_ruolo ur"
			 + "    	ON utentiPaginati.CODICE_FISCALE = ur.UTENTE_ID "
			 + "    LEFT JOIN ruolo ruolo "
			 + "        ON ruolo.CODICE = ur.RUOLO_CODICE ",
		nativeQuery = true)
	public Set<UtenteEntity> findUtentiByFiltriPerDownload(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike,
			@Param(value = "ruoli") List<String> ruoli,
			@Param(value = "stati") List<String> stati);

	@Query(value = ""
			+ "SELECT * FROM ( "
			+ "		SELECT * "
			+ "     	FROM ( "
			+ "            SELECT distinct rdg.CF_UTENTE "
			+ "                 FROM referente_delegati_gestore_programma  rdg "
			+ "                 	INNER JOIN programma programma"
			+ "                     	ON rdg.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdgp.CF_UTENTE"
			+ "                 FROM referente_delegati_gestore_progetto rdgp"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON rdgp.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                 	ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'  "
			+ " "
			+ "               UNION  "
			+ " "
			+ "             SELECT distinct rdp.CF_UTENTE"
			+ "                 FROM referente_delegati_partner rdp"
			+ "                 INNER JOIN ente_partner ep"
			+ "                     ON rdp.ID_PROGETTO = ep.ID_PROGETTO"
			+ "                 INNER JOIN progetto progetto"
			+ "                     ON ep.ID_PROGETTO = progetto.ID"
			+ "                 INNER JOIN programma programma"
			+ "                     ON progetto.ID_PROGRAMMA = programma.ID"
			+ "                 WHERE programma.POLICY = 'SCD'"
			+ " "
			+ "              UNION "
			+ " "
			+ "              SELECT distinct espf.ID_FACILITATORE"
			+ "                 FROM ente_sede_progetto_facilitatore espf"
			+ "              WHERE espf.RUOLO_UTENTE = 'VOL'"
			+ "			) AS utenti_per_ruolo  "
			+ "         	INNER JOIN utente utente"
			+ "             	ON utenti_per_ruolo.CF_UTENTE = utente.CODICE_FISCALE"
			+ " "
			+ "             WHERE 1=1"
			+ "                   AND    (    :criterioRicerca IS NULL   "
			+ "                   		   OR CONVERT( utente.ID, CHAR ) = :criterioRicerca  "
			+ "                            OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike )  "
			+ "                            OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "                      )"
			+ "                	  AND"
			+ "                   ( SELECT distinct u2.id"
			+ "                       FROM utente u2"
			+ "                          LEFT JOIN utente_x_ruolo ur2"
			+ "                             ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "                          LEFT JOIN ruolo ruolo2"
			+ "                             ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "                      WHERE 1=1"
			+ "                          AND u2.id = utente.id"
			+ "                          AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN ( :ruoli) )) = utente.id"
			+ "             ORDER BY utente.id"
			+ "            ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur"
			+ "                   ON ur.UTENTE_ID = risultato.CODICE_FISCALE"
			+ "             INNER JOIN ruolo ruolo   "
			+ "                   ON ruolo.CODICE = ur.RUOLO_CODICE  ",
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerDSCUPerDownload(
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_programma rdg "
			+ "			 	WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 		AND rdg.CF_UTENTE != :cfUtente"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "			 	FROM referente_delegati_gestore_progetto rdgp "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON rdgp.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "			 	FROM referente_delegati_partner rdp "
			+ "			 	INNER JOIN ente_partner ep "
			+ "			 		ON rdp.ID_PROGETTO = ep.ID_PROGETTO "
			+ "			 	INNER JOIN progetto progetto "
			+ "			 		ON ep.ID_PROGETTO = progetto.ID "
			+ "			 	WHERE progetto.ID_PROGRAMMA = :idProgramma "
			+ "             UNION"
			+ "             SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID_PROGRAMMA = :idProgramma"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             			OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					   )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			      ORDER BY utente.id"
			+ "               ) as risultato"
			+ "             INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoGestoreProgrammaPerDownload(
			@Param(value = "idProgramma") Long idProgramma, 
			@Param(value = "cfUtente")String cfUtente,
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE "
			+ "			   FROM referente_delegati_gestore_programma rdg "
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma"
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp"
			+ "				WHERE rdgp.CF_UTENTE != :cfUtente "
			+ "					AND rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			 SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.ID_PROGETTO = :idProgetto "
			+ "          UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "					AND	 ( :criterioRicerca IS NULL  "
			+ "					    OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "						)"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			             	FROM utente u2"
			+ "			                LEFT JOIN utente_x_ruolo ur2"
			+ "			                	ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                LEFT JOIN ruolo ruolo2"
			+ "			                    ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                WHERE 1=1"
			+ "			                    AND u2.id = utente.id"
			+ "			                    AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "                          ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE", 
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoGestoreProgettiPerDownload(
			@Param(value = "idProgramma") Long idProgramma,
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente, 
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli);

	@Query(value = "SELECT * FROM ( "
			+ "	SELECT * FROM ("
			+ "			 SELECT distinct rdg.CF_UTENTE"
			+ "				FROM referente_delegati_gestore_programma rdg"
			+ "				WHERE rdg.ID_PROGRAMMA = :idProgramma "
			+ "			 UNION "
			+ "			 SELECT distinct rdgp.CF_UTENTE "
			+ "				FROM referente_delegati_gestore_progetto rdgp "
			+ "				WHERE rdgp.ID_PROGETTO = :idProgetto"
			+ "			 UNION "
			+ "			SELECT distinct rdp.CF_UTENTE "
			+ "				FROM referente_delegati_partner rdp "
			+ "				WHERE rdp.CF_UTENTE != :cfUtente"
			+ "					AND rdp.ID_PROGETTO = :idProgetto"
			+ "                UNION"
			+ "			 SELECT distinct espf.id_facilitatore"
			+ "                FROM ente_sede_progetto_facilitatore espf"
			+ "                INNER JOIN progetto progetto"
			+ "					ON espf.ID_PROGETTO = progetto.ID"
			+ "				WHERE progetto.ID = :idProgetto"
			+ "                )"
			+ "			 	AS utenti_per_ruolo "
			+ "			 	INNER JOIN utente utente "
			+ "			 		ON utenti_per_ruolo.CF_UTENTE = utente.codice_fiscale"
			+ "			 	 "
			+ "			 	WHERE 1 = 1 "
			+ "			   		AND	 ( :criterioRicerca IS NULL  "
			+ "						OR CONVERT(utente.ID, CHAR) = :criterioRicerca "
			+ "	         	        OR UPPER( utente.NOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.COGNOME ) LIKE UPPER( :criterioRicercaLike ) "
			+ "             		OR UPPER( utente.CODICE_FISCALE ) LIKE UPPER( :criterioRicercaLike )"
			+ "					  	 )"
			+ "			 		AND  "
			+ "                    ( SELECT distinct u2.id"
			+ "			                        FROM utente u2"
			+ "			                           LEFT JOIN utente_x_ruolo ur2"
			+ "			                              ON u2.CODICE_FISCALE = ur2.UTENTE_ID"
			+ "			                           LEFT JOIN ruolo ruolo2"
			+ "			                              ON ruolo2.CODICE = ur2.RUOLO_CODICE"
			+ "			                       WHERE 1=1"
			+ "			                           AND u2.id = utente.id"
			+ "			                           AND  ( COALESCE(:ruoli) IS NULL   OR   ruolo2.nome IN (:ruoli) )) = utente.id"
			+ "			              ORDER BY utente.id"
			+ "                      ) as risultato"
			+ "                    INNER JOIN utente_x_ruolo ur "
			+ "			 		ON ur.UTENTE_ID = risultato.CODICE_FISCALE "
			+ "			 	    INNER JOIN ruolo ruolo "
			+ "			 		ON ruolo.CODICE = ur.RUOLO_CODICE",
			nativeQuery = true)
	public Set<UtenteEntity> findUtentiPerReferenteDelegatoEntePartnerProgettiPerDownload(
			@Param(value = "idProgramma") Long idProgramma,
			@Param(value = "idProgetto") Long idProgetto,
			@Param(value = "cfUtente")String cfUtente, 
			@Param(value = "criterioRicerca") String criterioRicerca,
			@Param(value = "criterioRicercaLike") String criterioRicercaLike, 
			@Param(value = "ruoli") List<String> ruoli);

}