export interface CSVRecord {
  [key: string]: string;
  IDFacilitatore: string;
  NominativoFacilitatore: string;
  IDSede: string;
  NominativoSede: string;
  AN1?: string;
  AN2?: string;
  AN3: string;
  AN4?: string;
  AN5?: string;
  AN6?: string;
  AN7: string;
  AN8: string;
  AN9: string;
  AN10: string;
  AN11: string;
  AN12: string;
  AN14?: string;
  AN17?: string;
  PR1?: string;
  PR2?: string;
  ES1?: string;
  ES2?: string;
  ES3?: string;
  ES4?: string;
  ES5?: string;
  ES6?: string;
  SE1: string;
  SE2: string;
  SE3: string;
  SE4: string;
  SE5: string;
  SE6?: string;
  SE7?: string;
}
